package modelo.entidades;
// Generated 24-may-2020 23:42:29 by Hibernate Tools 4.3.1



/**
 * Anunciante generated by hbm2java
 */
public class Anunciante  implements java.io.Serializable {


     private Integer id;
     private Anuncio anuncio;
     private String nombre;
     private String direccion;
     private String email;

    public Anunciante() {
    }

    public Anunciante(Anuncio anuncio, String nombre, String direccion, String email) {
       this.anuncio = anuncio;
       this.nombre = nombre;
       this.direccion = direccion;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Anuncio getAnuncio() {
        return this.anuncio;
    }
    
    public void setAnuncio(Anuncio anuncio) {
        this.anuncio = anuncio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


