package modelo.entidades;
// Generated 27-may-2020 20:52:56 by Hibernate Tools 4.3.1



/**
 * Anuncio generated by hbm2java
 */
public class Anuncio  implements java.io.Serializable {


     private Integer id;
     private int idAnunciante;
     private String contenido;
     private float precio;
     private Anunciante anunciante;

    public Anuncio() {
    }

	
    public Anuncio(int idAnunciante, String contenido, float precio) {
        this.idAnunciante = idAnunciante;
        this.contenido = contenido;
        this.precio = precio;
    }
    public Anuncio(int idAnunciante, String contenido, float precio, Anunciante anunciante) {
       this.idAnunciante = idAnunciante;
       this.contenido = contenido;
       this.precio = precio;
       this.anunciante = anunciante;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdAnunciante() {
        return this.idAnunciante;
    }
    
    public void setIdAnunciante(int idAnunciante) {
        this.idAnunciante = idAnunciante;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Anunciante getAnunciante() {
        return this.anunciante;
    }
    
    public void setAnunciante(Anunciante anunciante) {
        this.anunciante = anunciante;
    }




}


