package modelo.entidades;
// Generated 28-may-2020 22:53:01 by Hibernate Tools 4.3.1

/**
 * Anunciante generated by hbm2java
 */
public class Anunciante implements java.io.Serializable {

    private Integer id;
    private Anuncio anuncioById;
    private Anuncio anuncioByIdAnunciante;
    private String nombre;
    private String direccion;
    private String email;

    public Anunciante() {
    }

    public Anunciante(String nombre, String direccion, String email) {
        this.anuncioById = anuncioById;
        this.anuncioByIdAnunciante = anuncioByIdAnunciante;
        this.nombre = nombre;
        this.direccion = direccion;
        this.email = email;
    }

    public Anunciante(Anuncio anuncioById, Anuncio anuncioByIdAnunciante, String nombre, String direccion, String email) {
        this.anuncioById = anuncioById;
        this.anuncioByIdAnunciante = anuncioByIdAnunciante;
        this.nombre = nombre;
        this.direccion = direccion;
        this.email = email;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Anuncio getAnuncioById() {
        return this.anuncioById;
    }

    public void setAnuncioById(Anuncio anuncioById) {
        this.anuncioById = anuncioById;
    }

    public Anuncio getAnuncioByIdAnunciante() {
        return this.anuncioByIdAnunciante;
    }

    public void setAnuncioByIdAnunciante(Anuncio anuncioByIdAnunciante) {
        this.anuncioByIdAnunciante = anuncioByIdAnunciante;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

}
