package modelo.entidades;
// Generated 31-may-2020 13:38:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ClaveTemporal generated by hbm2java
 */
public class ClaveTemporal  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String contrasenya;
     private Date fechaDeCreacion;

    public ClaveTemporal() {
    }

    public ClaveTemporal(Usuario usuario, String contrasenya, Date fechaDeCreacion) {
       this.usuario = usuario;
       this.contrasenya = contrasenya;
       this.fechaDeCreacion = fechaDeCreacion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getContrasenya() {
        return this.contrasenya;
    }
    
    public void setContrasenya(String contrasenya) {
        this.contrasenya = contrasenya;
    }
    public Date getFechaDeCreacion() {
        return this.fechaDeCreacion;
    }
    
    public void setFechaDeCreacion(Date fechaDeCreacion) {
        this.fechaDeCreacion = fechaDeCreacion;
    }




}


