package modelo.entidades;
// Generated 24-may-2020 23:42:29 by Hibernate Tools 4.3.1



/**
 * Configuracion generated by hbm2java
 */
public class Configuracion  implements java.io.Serializable {


     private Integer id;
     private Usuario usuarioByIdUsuario;
     private Usuario usuarioByIdConfiguracion;

    public Configuracion() {
    }

    public Configuracion(Usuario usuarioByIdUsuario, Usuario usuarioByIdConfiguracion) {
       this.usuarioByIdUsuario = usuarioByIdUsuario;
       this.usuarioByIdConfiguracion = usuarioByIdConfiguracion;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuarioByIdUsuario() {
        return this.usuarioByIdUsuario;
    }
    
    public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
        this.usuarioByIdUsuario = usuarioByIdUsuario;
    }
    public Usuario getUsuarioByIdConfiguracion() {
        return this.usuarioByIdConfiguracion;
    }
    
    public void setUsuarioByIdConfiguracion(Usuario usuarioByIdConfiguracion) {
        this.usuarioByIdConfiguracion = usuarioByIdConfiguracion;
    }




}


