package modelo.entidades;
// Generated 31-may-2020 13:38:34 by Hibernate Tools 4.3.1



/**
 * Entrada generated by hbm2java
 */
public class Entrada  implements java.io.Serializable {


     private Integer id;
     private Evento evento;
     private Usuario usuario;
     private float precio;

    public Entrada() {
    }

    public Entrada(Evento evento, Usuario usuario, float precio) {
       this.evento = evento;
       this.usuario = usuario;
       this.precio = precio;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }




}


