package modelo.entidades;
// Generated 24-may-2020 23:42:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private Oferta oferta;
     private int idUsuario;
     private String nombre;
     private String descripcion;
     private String lugar;
     private Set ofertas = new HashSet(0);
     private Usuario usuario;
     private Set entradas = new HashSet(0);

    public Evento() {
    }

	
    public Evento(Oferta oferta, int idUsuario, String nombre, String descripcion, String lugar) {
        this.oferta = oferta;
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.lugar = lugar;
    }
    public Evento(Oferta oferta, int idUsuario, String nombre, String descripcion, String lugar, Set ofertas, Usuario usuario, Set entradas) {
       this.oferta = oferta;
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.lugar = lugar;
       this.ofertas = ofertas;
       this.usuario = usuario;
       this.entradas = entradas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


