package modelo.entidades;
// Generated 28-may-2020 22:53:01 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer id;
     private int idUsuario;
     private String nombre;
     private String descripcion;
     private String lugar;
     private Set ofertas = new HashSet(0);
     private Set eventoCategorias = new HashSet(0);
     private Set entradas = new HashSet(0);

    public Evento() {
    }

	
    public Evento(int idUsuario, String nombre, String descripcion, String lugar) {
        this.idUsuario = idUsuario;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.lugar = lugar;
    }
    public Evento(int idUsuario, String nombre, String descripcion, String lugar, Set ofertas, Set eventoCategorias, Set entradas) {
       this.idUsuario = idUsuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.lugar = lugar;
       this.ofertas = ofertas;
       this.eventoCategorias = eventoCategorias;
       this.entradas = entradas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }
    public Set getEventoCategorias() {
        return this.eventoCategorias;
    }
    
    public void setEventoCategorias(Set eventoCategorias) {
        this.eventoCategorias = eventoCategorias;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }




}


