package modelo.entidades;
// Generated 31-may-2020 19:26:09 by Hibernate Tools 4.3.1



/**
 * EventoCategoria generated by hbm2java
 */
public class EventoCategoria  implements java.io.Serializable {


     private EventoCategoriaId id;
     private Categoria categoria;
     private Evento evento;

    public EventoCategoria() {
    }

    public EventoCategoria(EventoCategoriaId id, Categoria categoria, Evento evento) {
       this.id = id;
       this.categoria = categoria;
       this.evento = evento;
    }
   
    public EventoCategoriaId getId() {
        return this.id;
    }
    
    public void setId(EventoCategoriaId id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }




}


