package modelo.entidades;
// Generated 24-may-2020 23:42:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer id;
     private Evento evento;
     private float descuento;
     private Date TInicio;
     private Date TFin;
     private Set eventos = new HashSet(0);

    public Oferta() {
    }

	
    public Oferta(Evento evento, float descuento, Date TInicio, Date TFin) {
        this.evento = evento;
        this.descuento = descuento;
        this.TInicio = TInicio;
        this.TFin = TFin;
    }
    public Oferta(Evento evento, float descuento, Date TInicio, Date TFin, Set eventos) {
       this.evento = evento;
       this.descuento = descuento;
       this.TInicio = TInicio;
       this.TFin = TFin;
       this.eventos = eventos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public float getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(float descuento) {
        this.descuento = descuento;
    }
    public Date getTInicio() {
        return this.TInicio;
    }
    
    public void setTInicio(Date TInicio) {
        this.TInicio = TInicio;
    }
    public Date getTFin() {
        return this.TFin;
    }
    
    public void setTFin(Date TFin) {
        this.TFin = TFin;
    }
    public Set getEventos() {
        return this.eventos;
    }
    
    public void setEventos(Set eventos) {
        this.eventos = eventos;
    }




}


